spring.application.name=medischeduler-routeservice
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.auto.create.topics.enable=false
spring.kafka.producer.linger.ms=10
spring.kafka.producer.batch.size=32768
spring.kafka.producer.retries=5
spring.kafka.producer.retry-backoff=100 
spring.kafka.producer.acks=all
spring.kafka.producer.max-in-flight=1
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id:student_teacher_pairs
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.replication_factor=3
spring.kafka.broker.min.insync.replicas=2
spring.redis.host=redis-14478.crce174.ca-central-1-1.ec2.redns.redis-cloud.com
spring.redis.port=14478
spring.redis.username=default
spring.redis.password=ygZGA19ayW4QrMOfBInZ9TUW0ZAhj9mS
spring.redis.client-type=jedis
spring.redis.jedis.pool.max-active=10
spring.redis.jedis.pool.max-idle=5
spring.redis.jedis.pool.min-idle=1
spring.redis.jedis.pool.max-wait=3000ms

#backoff in ms