package dfm.medischeduler_schedulerservice;

import org.springframework.context.annotation.Configuration;
import org.springframework.messaging.simp.config.MessageBrokerRegistry;
import org.springframework.web.socket.config.annotation.EnableWebSocketMessageBroker;
import org.springframework.web.socket.config.annotation.StompEndpointRegistry;
import org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurer;

/**
 * WebSocket configuration for real-time assignment delivery.
 *
 * Enables a STOMP-based message broker so that the frontend can subscribe
 * to {@code /topic/{clientId}/upload/assignments} and receive optimal
 * assignments as they are generated by the OR-Tools solver.
 *
 * The {@code /assignments} endpoint supports both raw WebSocket and
 * SockJS fallback for broad browser compatibility.
 */
@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {

    @Override
    public void configureMessageBroker(MessageBrokerRegistry config) {
        config.enableSimpleBroker("/topic");
        config.setApplicationDestinationPrefixes("/upload");
    }

    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry.addEndpoint("/assignments").setAllowedOriginPatterns("*");
        registry.addEndpoint("/assignments").setAllowedOriginPatterns("*").withSockJS();
    }
}
